# Generated by Django 3.2.8 on 2021-10-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211021_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='code_gerister',
            new_name='code_register',
        ),
    ]
